[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "python-google-sheets"
description = "A lightweight and efficient Python wrapper for the Google Sheets API v4"
authors = [{ name = "Timofey Egorov", email = "timegorr@gmail.com" }]
version = "1.2.0"
readme = "README.md"
requires-python = ">=3.11"
keywords = ["spreadsheets", "google-spreadsheets", "google-sheets", "api", "wrapper", "python", "pydantic"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "google-auth",
    "google-api-python-client",
    "pydantic>=2.0.0",
]
license = "MIT"
license-files = ["LICENSE*"]

[project.urls]
Homepage = "https://github.com/Timofey28/python-google-sheets"
Issues = "https://github.com/Timofey28/python-google-sheets/issues"