[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "python-google-sheets"
description = "A lightweight and efficient Python wrapper for the Google Sheets API v4"
authors = [{ name = "Timofey Egorov", email = "timegorr@gmail.com" }]
version = "1.1.0"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "google-auth",
    "google-api-python-client",
    "pydantic>=2.0.0",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]